version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      ignore:
          - update-types: ["version-update:semver-patch"]
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "fix"
          prefix-development: "chore"
          include: "scope"
