name: Dependabot Auto Merge
on:
    workflow_run:
        workflows: ["Integration"]
        branches: ["dependabot/**"]
        types: [completed]
jobs:
    dependabot-auto-merge:
        name: Auto Merge PR
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v2
            - uses: ahmadnassri/action-dependabot-auto-merge@v2
              with:
                  target: minor
                  github-token: ${{ secrets.GH_TOKEN }}
