name: Deployment
on:
    release:
        types: [released]
jobs:
    deploy-release:
        name: Deploy Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - uses: actions/cache@v3.0.7
              with:
                  path: node_modules
                  key: node-modules-${{ hashFiles('package-lock.json') }}
            - run: npm install
            - run: npm run build:production
            - run: npm run deploy
              env:
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
