name: Deployment
on:
    release:
        types: [released]
env:
    NODE_VERSION: 22.13.1
jobs:
    deploy-release:
        name: Deploy Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v4
              with:
                  path: node_modules
                  key: node-modules-${{ hashFiles('package-lock.json') }}
            - run: npm install
            - run: npm run build:production
            - run: npm run deploy
              env:
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
