name: Integration
on:
    - push
    - workflow_call
jobs:
    install-lint-test-build-release:
        name: Install, Lint, Test, Build, and Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - uses: actions/cache@v2
              with:
                  path: node_modules
                  key: node-modules-${{ hashFiles('package-lock.json') }}
            - run: npm install
            - run: npm run format:check
            - run: npm run lint:check
            - run: npm run test
            - run: npm run build
            - run: npm run release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
