name: Integration
on: [push]
jobs:
    install-lint-test-build:
        name: Install, Lint, Test, and Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - uses: actions/cache@v2
              with:
                  path: node_modules
                  key: node-modules-${{ hashFiles('package-lock.json') }}
            - run: npm install
            - run: npm run format:check
            - run: npm run lint:check
            - run: npm run test
            - run: npm run build
    release:
        name: Release
        needs: install-lint-test-build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - uses: actions/cache@v2
              with:
                  path: node_modules
                  key: node-modules-${{ hashFiles('package-lock.json') }}
            - run: npm install
            - run: npm run release
              env:
                  GIT_CREDENTIALS: ${{ secrets.GH_TOKEN }}
